name: Deploy mfe-produtos

on:
  push:
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mfe-produtos

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 👇 Angular CLI pede Node >= 20.19 (ou 22.12). Vamos de 20.19.x
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Get pnpm store path
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Restore pnpm store from cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-mfe-produtos-${{ hashFiles('mfe-produtos/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-mfe-produtos-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build (Angular)
        run: |
          pnpm exec ng version || true
          pnpm exec ng build --configuration production --output-path dist
          # Se for Project Pages, use base-href:
          # pnpm exec ng build --configuration production --output-path dist --base-href "/poc-microfrontends/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: mfe-produtos/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
