name: Deploy mfe-produtos

on:
  push:
    branches: ['**']   # roda em qualquer branch; ajuste se quiser
  workflow_dispatch:    # permite rodar manualmente

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Tudo roda dentro da pasta do app
    defaults:
      run:
        working-directory: mfe-produtos

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Get pnpm store path
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Restore pnpm store from cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-mfe-produtos-${{ hashFiles('mfe-produtos/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-mfe-produtos-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build (Angular)
        run: |
            pnpm exec ng version || true
            pnpm exec ng build --configuration production --output-path dist
        # Se precisar base-href (Project Pages), troque a linha acima por:
        # pnpm exec ng build --configuration production --output-path dist --base-href "/<nome-do-repo>/"

      # === Publique no GitHub Pages (opcional). Ative Pages em Settings → Pages → Build & deployment: GitHub Actions
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: mfe-produtos/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
