name: CI (monorepo)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm


      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

 
      - name: pnpm fetch
        run: pnpm fetch


      - name: Install dependencies
        run: pnpm install --frozen-lockfile

 
      - name: Lint
        run: pnpm lint
        continue-on-error: true  

      - name: Test
        run: pnpm test -- --ci --reporters=default

      - name: Build
        run: pnpm build
