name: CI (Monorepo)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      # 👇 Este passo é essencial — instala o pnpm antes de qualquer uso
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # use a versão que seu projeto usa (verifique no packageManager ou package.json)
          run_install: false

      # (opcional, mas acelera instalação em monorepos)
      - name: Fetch store cache
        run: pnpm fetch

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
